framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/resource/translations'
        paths:
            - '%kernel.project_dir%/resource/js'    # JavaScript files
        fallbacks:
            - en
        providers:
            lokalise:
                dsn: '%env(LOKALISE_DSN)%'
                locales: ['ar', 'da', 'de', 'en', 'es', 'fa', 'fi', 'fr', 'fy', 'it', 'lv', 'nb', 'nl', 'nn', 'pl', 'pt_BR', 'pt', 'ru', 'se', 'sv', 'zh']
                domains: ['messages']
