---
engines:
  csslint:
    enabled: true
    checks:
      ids:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "resource/css/*.css"
  - "resource/js/*.js"
  - "model/**/*.php"
  - "controller/**/*.php"
  - "index.php"
  - "rest.php"
exclude_paths:
- resource/js/bootstrap-multiselect.js
- resource/js/*min.js
- resource/css/jquery.mCustomScrollbar.css
- resource/fonts/**/*
- resource/pics/**/*
- resource/translations/**/*
- tests/**/*
- view/**/*
- tools/**/*
- LICENSE
- README.md
- composer.json 
- config.ttl.dist
- favicon.ico 
- phpdoc.sh 
- phpunit.xml
