#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
// use App\Command\TranslationPullCommand;

$application = new Application();
$application->run();


