# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
# parameters:
    # your_custom_code_paths:
    #     - '%kernel.project_dir%/src'
    #     - '%kernel.project_dir%/resource/js'
    # locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    LinkUrlExtension:
        class: 'LinkUrlExtension'
        public: true
    
    Translation\Extractor\JsTranslationExtractor:
        arguments:
            $directory: '%kernel.project_dir%/resource/js'
        tags:
            - { name: 'translation.extractor', alias: 'js_translation_extractor' }
    
    # Symfony\Bundle\FrameworkBundle\Command\TranslationUpdateCommand:
    #     arguments:
    #         $writer: '@translation.writer'
    #         $reader: '@translation.reader'
    #         $extractor: '@translation.extractor'
    #         #$extractor: 'js_translation_extractor'
    #         $defaultLocale: 'en'
    #         $defaultTransPath: '%kernel.project_dir%/resource/translations' 
    #         $defaultViewsPath: '%kernel.project_dir%/src/view'
    #         $transPaths: [] 
    #         # $codePaths: '%your_custom_code_paths%'
    #         $codePaths: 
    #             - '%kernel.project_dir%/src'
    #             - '%kernel.project_dir%/resource/js'
    #         $enabledLocales: ['ar', 'da', 'de', 'en', 'es', 'fa', 'fi', 'fr', 'fy', 'it', 'lv', 'nb', 'nl', 'nn', 'pl', 'pt_BR', 'pt', 'ru', 'se', 'sv', 'zh'] 
