---
- hosts: all
  become: True
  gather_facts: False
  roles:
    - base
    - openjdk
    - fuseki
    - skosmos
  pre_tasks:
    - name: Install Unzip for Ansible
      raw: sudo apt-get install unzip
    - setup: # aka gather_facts
